# Generated by Django 2.1.5 on 2019-01-23 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20190123_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 16, 54, 3, 502427)),
        ),
    ]
