# Generated by Django 2.1.5 on 2019-01-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_auto_20190123_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='created_at',
            new_name='created',
        ),
    ]
