# Generated by Django 2.1.5 on 2019-01-23 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0009_auto_20190123_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 17, 17, 3, 592749)),
        ),
        migrations.AlterField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 17, 17, 3, 592749)),
        ),
    ]
