# Generated by Django 2.1.5 on 2019-01-23 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0014_auto_20190123_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
