# Generated by Django 2.1.5 on 2019-01-23 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0015_auto_20190123_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 12, 17, 25, 530101)),
        ),
    ]
