# Generated by Django 2.1.5 on 2019-01-23 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0016_auto_20190123_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 17, 48, 15, 788763)),
        ),
    ]
