# Generated by Django 2.1.5 on 2019-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0017_auto_20190123_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created',
            field=models.DateTimeField(default=None),
        ),
    ]
