# Generated by Django 2.1.5 on 2019-01-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0018_auto_20190123_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='created',
        ),
    ]
