# Generated by Django 2.1.5 on 2019-01-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0030_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
