# Generated by Django 2.1.5 on 2019-01-25 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0031_auto_20190125_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
