# Generated by Django 2.1.5 on 2019-01-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0034_auto_20190125_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='users',
            field=models.CharField(default='Siddhi', max_length=50),
        ),
    ]
