# Generated by Django 2.1.5 on 2019-01-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0035_auto_20190125_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='users',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
