# Generated by Django 2.1.5 on 2019-01-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0036_auto_20190125_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='completed',
            field=models.CharField(default='Not Completed', max_length=50),
        ),
    ]
